apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backsofi
  template:
    metadata:
      labels:
        app: backsofi
    spec:
      containers:
      - name: backsofi
        image: soficaucota/backsofi:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb+srv://masocaucota:caucotaAlways@cluster0.obhprab.mongodb.net/Ecommerce?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: backsofi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer